{{- range $count := until (int $.Values.clusterReplicas)}}
{{- $ocpVersion := $.Values.ocpVersion | replace "." "" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}-aws-creds
  namespace: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
stringData:
  aws_access_key_id: {{ $.Values.awsCredentials.accessKey }}
  aws_secret_access_key: {{ $.Values.awsCredentials.secretAccessKey }}
{{- end }}

