{{- range $count := until (int $.Values.clusterReplicas)}}
{{- $ocpVersion := $.Values.ocpVersion | replace "." "" }}
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
  namespace: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
spec:
  clusterName: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
  clusterNamespace: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
{{- end }}

