{{- define "install.config" }}
{{- $count := index . 0}}
{{- $ocpVersion := index . 1}}
{{- $clusterName := index . 2}}
{{- $baseDomain := index . 3}}
{{- $masterReplicas := index . 4}}
{{- $workerReplicas := index . 5}}
{{- $region := index . 6}}
{{- $sshKey := index . 7}}
apiVersion: v1
metadata:
  name: {{ $clusterName }}-{{ $ocpVersion }}-{{ $count }}
baseDomain: {{ $baseDomain }}
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: {{ $masterReplicas | default "1" }}
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.xlarge
compute:
- hyperthreading: Enabled
  architecture: amd64
  name: 'worker'
  replicas: {{ $workerReplicas | default "0" }}
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {{ $region }}
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
  {{ $sshKey }}
{{- end }}
{{- range $count := until (int $.Values.clusterReplicas) }}
{{- $ocpVersion := $.Values.ocpVersion | replace "." "" }}
{{- $sshKey := $.Files.Get "files/ssh_public_key" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}-install-config
  namespace: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
type: Opaque
data:
  install-config.yaml: {{ include "install.config" (list $count $ocpVersion $.Values.cluster.name $.Values.baseDomain $.Values.cluster.master.replicas $.Values.cluster.worker.replicas $.Values.region $sshKey) | b64enc }}
{{- end }}

