{{- range $count := until (int $.Values.clusterReplicas) }}
{{- $ocpVersion := $.Values.ocpVersion | replace "." "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}-pull-secret
  namespace: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
stringData:
  .dockerconfigjson: >-
    {{ $.Files.Get "files/pull-secret.json" }}
type: kubernetes.io/dockerconfigjson
{{- end }}

