{{- range $count := until (int $.Values.clusterReplicas) }}
{{- $ocpVersion := $.Values.ocpVersion | replace "." "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}-ssh-private-key
  namespace: {{ $.Values.cluster.name }}-{{ $ocpVersion }}-{{ $count }}
stringData:
  ssh-privatekey: {{ $.Files.Get "files/ssh_private_key" | b64enc }}
type: Opaque
{{- end }}
