version: 3
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest'
dependencies:
  galaxy: # requierments.yaml
    collections:
      - # collection name
  python:
    - #  python packages
  system: # bindep.txt
options:
  package_manager_path: /usr/bin/microdnf